### ISSUE TITLE
Performance enhancement

### ISSUE THREAD

**Issue by Tambup** [Tomawock/Climb_Training_Laravel#6]
Hi,

The mothods isIdExerciseBlocked, isIdTrainingprogramBlocked in app/DataLayer.php can be enhanced executing the count inside the query. Btw, can be a better idea to use eloquent to increase readability.

**Comment by Tomawock** [comment]
Thanks,
i will try to implement with eloquent asap, but currently we are working on the docs so the code will be modified later.
